# File: UseCUDA.cmake
# CMAKE commands to actually use the CUDA compiler
# Version: 0.0.1
#
# To use CUDA you have to fix NVSDKCOMPUTE_ROOT environment variable to
# the path of the Nvidia SDK.
#

SET(NVSDKCOMPUTE_ROOT $ENV{NVSDKCOMPUTE_ROOT})
IF(NOT NVSDKCOMPUTE_ROOT)
  MESSAGE(FATAL_ERROR "Need to define NVSDKCOMPUTE_ROOT")
ENDIF()

FIND_PACKAGE(CUDA QUIET REQUIRED)

#SET(CUDA_NVCC_FLAGS -arch=sm_11)

FIND_PATH(CUDA_CUT_INCLUDE_DIR
  cutil.h
  PATHS ${CUDA_SDK_SEARCH_PATH}
  PATH_SUFFIXES "common/inc"
  DOC "Location of cutil.h"
  NO_DEFAULT_PATH
  )
FIND_PATH(CUDA_CUT_INCLUDE_DIR cutil.h DOC "Location of cutil.h")
MARK_AS_ADVANCED(CUDA_CUT_INCLUDE_DIR)

IF(CMAKE_SIZEOF_VOID_P EQUAL 8)
  SET(CUDA_CUTIL_NAME cutil_x86_64)
  LINK_DIRECTORIES(${CUDA_TOOLKIT_ROOT_DIR}/lib64)
ELSE(CMAKE_SIZEOF_VOID_P EQUAL 8)
  SET(CUDA_CUTIL_NAME cutil_i386)
  LINK_DIRECTORIES(${CUDA_TOOLKIT_ROOT_DIR}/lib)
ENDIF(CMAKE_SIZEOF_VOID_P EQUAL 8)

FIND_LIBRARY(CUDA_CUT_LIBRARY
  NAMES cutil ${CUDA_CUTIL_NAME} cud
  PATHS ${CUDA_SDK_SEARCH_PATH}
  PATH_SUFFIXES "common/lib" "lib"
  DOC "Location of cutil library"
  NO_DEFAULT_PATH
  )
FIND_LIBRARY(CUDA_CUT_LIBRARY NAMES cutil ${CUDA_CUTIL_NAME} DOC "Location of cutil library")
MARK_AS_ADVANCED(CUDA_CUT_LIBRARY)
SET(CUDA_CUT_LIBRARIES ${CUDA_CUT_LIBRARY})

INCLUDE_DIRECTORIES(
  ${CUDA_INCLUDE_DIRS}
  ${CUDA_CUT_INCLUDE_DIR}
  )
LINK_LIBRARIES(${CUDA_CUT_LIBRARIES})
